version: "3.8"

name: vue-nest_dev

services:
  server:
    container_name: "vue-nest_server_dev"
    restart: always
    build: server
    command: npm run start:prod
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "vue-nest_nginx_dev"
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d
