FROM node:20

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install
RUN yarn global add @nestjs/cli

COPY . .

CMD [ -d "node_modules" ] && yarn dev || yarn install --frozen-lockfile && yarn dev