FROM node:18

ARG WWWGROUP
# выставляем права чтобы можно 
# созданные файлы через docker контейнер
# могли быть изменнены на хосте
USER $WWWUSER:$WWWUSER

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install
RUN yarn global add @nestjs/cli

COPY . .
RUN chown -R $WWWUSER:$WWWUSER ./node_modules

CMD [ -d "node_modules" ] && yarn dev || yarn install --frozen-lockfile && yarn dev